name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true 

env:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Djava.net.preferIPv4Stack=true"
  JAVA_TOOL_OPTIONS: "-Dfile.encoding=UTF-8"

jobs:
  test:
    name: Test and Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew

      - name: Validate Gradle Wrapper (with retry)
        run: |
          for i in {1..3}; do
            echo "Attempt $i: validating Gradle wrapper..."
            npx --yes gradle/wrapper-validation-action@v2 && break || sleep 10
          done
        continue-on-error: true

      - name: Setup Gradle with cache
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.14.3
          cache-disabled: false

      - name: Ensure Git metadata available for build
        run: |
          git fetch --unshallow || true
          git rev-parse --short HEAD

      - name: Run Lint and Checkstyle (if configured)
        run: ./gradlew check --continue --stacktrace

      - name: Run Unit Tests
        run: ./gradlew test --info --stacktrace

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            **/build/reports/tests/test/
            **/build/test-results/test/

  build:
    name: Build and Package
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew

      - name: Setup Gradle with cache
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.14.3

      - name: Build project (skip tests)
        run: ./gradlew clean build -x test --stacktrace

      - name: Upload Build Artifact (JAR/WAR)
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: |
            **/build/libs/*.jar
            **/build/distributions/*.zip
